config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :show, :edit]

  root "games#index"

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :home_team, class_name: "Team"
  belongs_to :away_team, class_name: "Team"

  has_many :innings, -> { order(number: :asc) }

  enum status: [:scheduled, :running, :final]

  def is_winner?(team)
    if home_team == team
      home_team_runs > away_team_runs
    else
      away_team_runs > home_team_runs
    end
  end

  def home_team_runs
    innings.sum(:home_team_runs)
  end

  def away_team_runs
    innings.sum(:away_team_runs)
  end

  def home_team_hits
    innings.sum(:home_team_hits)
  end

  def away_team_hits
    innings.sum(:away_team_hits)
  end

  def home_team_errors
    innings.sum(:home_team_errors)
  end

  def away_team_errors
    innings.sum(:away_team_errors)
  end
end

app/models/inning.rb
class Inning < ApplicationRecord
  belongs_to :game
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :home_games, class_name: "Game", foreign_key: :home_team_id
  has_many :away_games, class_name: "Game", foreign_key: :away_team_id

  def wins
    played_games.select { |g| g.is_winner? self }.count
  end

  def losses
    played_games.reject { |g| g.is_winner? self }.count
  end

  def percentage
    wins + losses > 0 ? (1.0 * wins / (wins + losses)) : 0
  end

  def games_behind(other)
    ((other.wins - self.wins) + (self.losses - other.losses)) / 2.0
  end

  def home_runs
    home_games.to_a.sum(&:home_team_runs)
  end

  def away_runs
    away_games.to_a.sum(&:away_team_runs)
  end

  def points_for
    home_games.to_a.sum(&:home_team_runs) + away_games.to_a.sum(&:away_team_runs)
  end

  def points_against
    home_games.to_a.sum(&:away_team_runs) + away_games.to_a.sum(&:home_team_runs)
  end

  def difference
    points_for - points_against
  end

  def games
    Game.where(home_team: self).or(Game.where(away_team: self))
  end

  def played_games
    games.where(status: :final)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:show, :edit]

  def index
    @games = Game.all.includes(:home_team, :away_team).order(:started_at)
    @teams = Team.all.sort_by { |team| -team.percentage }
  end

  def show
  end

  def edit
  end

  private

  def find_game
    @game = Game.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/edit.html.erb
<div data-channel="games" data-game-id="<%= @game.id %>">
  <p><%= link_to "Back to Games", games_path %></p>
  <h2 class="text-center"><%= @game.started_at.to_s(:short) %> – <%= @game.home_team.name %> vs. <%= @game.away_team.name %></h2>
  <br>
  <table class="table table-bordered" style="font-size: 1.75rem; width: 400px; margin: auto;">
    <tbody>
      <tr>
        <td><%= @game.home_team.name %></td>
        <td id="home-team-runs"><%= @game.home_team_runs %></td>
        <td id="home-team-hits"><%= @game.home_team_hits %></td>
        <td id="home-team-errors"><%= @game.home_team_errors %></td>
      </tr>
      <tr>
        <td><%= @game.away_team.name %></td>
        <td id="away-team-runs"><%= @game.away_team_runs %></td>
        <td id="away-team-hits"><%= @game.away_team_hits %></td>
        <td id="away-team-errors"><%= @game.away_team_errors %></td>
      </tr>
    </tbody>
  </table>

  <div class="innings" style="width: 500px; margin: auto;">
    <div class="inning-header row">
      <div class="col-sm-2">Inning #</div>
      <div class="col-sm-5">Home Team</div>
      <div class="col-sm-5">Away Team</div>
    </div>
    <% @game.innings.each do |inning| %>
      <div class="inning text-center row" data-inning-id="<%= inning.id %>">
        <div class="number col-sm-2"><%= inning.number %></div>
        <div class="team col-sm-5" data-team="home">
          <div class="row type" data-type="runs" data-value="<%= inning.home_team_runs || 0 %>">
            <div class="col-sm-3">R</div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default subtract">-</button>
            </div>
            <div class="col-sm-2 text-center value">
              <%= inning.home_team_runs || "-" %>
            </div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default add">+</button>
            </div>
          </div>
          <div class="row type" data-type="hits" data-value="<%= inning.home_team_hits || 0 %>">
            <div class="col-sm-3">H</div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default subtract">-</button>
            </div>
            <div class="col-sm-2 text-center value">
              <%= inning.home_team_hits || "-" %>
            </div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default add">+</button>
            </div>
          </div>
          <div class="row type" data-type="errors" data-value="<%= inning.home_team_errors || 0 %>">
            <div class="col-sm-3">E</div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default subtract">-</button>
            </div>
            <div class="col-sm-2 text-center value">
              <%= inning.home_team_errors || "-" %>
            </div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default add">+</button>
            </div>
          </div>
        </div>
        <div class="team col-sm-5" data-team="away">
          <div class="row type" data-type="runs" data-value="<%= inning.away_team_runs || 0 %>">
            <div class="col-sm-3">R</div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default subtract">-</button>
            </div>
            <div class="col-sm-2 text-center value">
              <%= inning.home_team_runs || "-" %>
            </div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default add">+</button>
            </div>
          </div>
          <div class="row type" data-type="hits" data-value="<%= inning.away_team_hits || 0 %>">
            <div class="col-sm-3">H</div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default subtract">-</button>
            </div>
            <div class="col-sm-2 text-center value">
              <%= inning.home_team_hits || "-" %>
            </div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default add">+</button>
            </div>
          </div>
          <div class="row type" data-type="errors" data-value="<%= inning.away_team_errors || 0 %>">
            <div class="col-sm-3">E</div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default subtract">-</button>
            </div>
            <div class="col-sm-2 text-center value">
              <%= inning.home_team_errors || "-" %>
            </div>
            <div class="col-sm-3">
              <button class="btn btn-sm btn-default add">+</button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/games/index.html.erb
<h2>Standings</h2>

<table class="table table-bordered table-striped" style="font-size: 1.5rem; text-align: right">
  <thead>
    <tr>
      <th>TEAM</th>
      <th style="width: 75px; text-align: right;">W</th>
      <th style="width: 75px; text-align: right;">L</th>
      <th style="width: 75px; text-align: right;">PCT.</th>
      <th style="width: 75px; text-align: right;">GB</th>
      <th style="width: 125px; text-align: right; border-left: 1px solid #ddd;">HOME</th>
      <th style="width: 125px; text-align: right;">ROAD</th>
      <th style="width: 100px; text-align: right; border-left: 1px solid #ddd;">RS</th>
      <th style="width: 100px; text-align: right;">RA</th>
      <th style="width: 100px; text-align: right;">DIFF</th>
    </tr>
  </thead>
  <tbody>
    <% previous_team = nil %>
    <% @teams.each do |team| %>
      <tr>
        <td style="text-align: left;"><%= team.name %></td>
        <td><%= team.wins %></td>
        <td><%= team.losses %></td>
        <td><%= team.percentage.round(3) %></td>
        <td><%= (previous_team && team.played_games.count > 0) ? team.games_behind(previous_team).round(1) : "–" %></td>
        <td style="border-left: 1px solid #ddd;"><%= team.home_runs %></td>
        <td><%= team.away_runs %></td>
        <td style="border-left: 1px solid #ddd;"><%= team.points_for %></td>
        <td><%= team.points_against %></td>
        <td style="color: <%= team.difference > 0 ? "#0C0" : "#C00" %>;"><%= team.difference > 0 ? "+#{team.difference}" : team.difference %></td>
      </tr>
      <% previous_team = team %>
    <% end %>
  </tbody>

</table>

<hr>

<h2>Games</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th style="width: 150px">Game Date</th>
      <th style="width: 300px">Teams</th>
      <th style="width: 50px">R</th>
      <th style="width: 50px">H</th>
      <th style="width: 50px">E</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr class="game-<%= game.id %> home" >
        <td rowspan="2" style="vertical-align: middle; font-size: 2rem;">
          <%= link_to game.started_at.to_s(:short), game %>
        </td>
        <td style="vertical-align: middle; font-size: 2rem;"><%= game.home_team.name %> (<%= game.is_winner? game.home_team %>)</td>
        <td style="vertical-align: middle; font-size: 2rem;" class="runs" ><%= game.home_team_runs %></td>
        <td style="vertical-align: middle; font-size: 2rem;" class="hits" ><%= game.home_team_hits %></td>
        <td style="vertical-align: middle; font-size: 2rem;" class="errors" ><%= game.home_team_errors %></td>
        <td rowspan="2" class="text-right" style="vertical-align: middle;">
          <%= link_to "Admin", edit_game_path(game), class: "btn btn-default" %>
        </td>
      </tr>
      <tr class="game-<%= game.id %> away" >
        <td style="vertical-align: middle; font-size: 2rem;"><%= game.away_team.name %> (<%= game.is_winner? game.away_team %>)</td>
        <td style="vertical-align: middle; font-size: 2rem;" class="runs" ><%= game.away_team_runs %></td>
        <td style="vertical-align: middle; font-size: 2rem;" class="hits" ><%= game.away_team_hits %></td>
        <td style="vertical-align: middle; font-size: 2rem;" class="errors" ><%= game.away_team_errors %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/show.html.erb
<div data-channel="games" data-game-id="<%= @game.id %>" >
  <p><%= link_to "Back to Games", games_path %></p>
  <h2><%= @game.started_at.to_s(:short) %> – <%= @game.home_team.name %> vs. <%= @game.away_team.name %></h2>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <table class="table table-bordered" style="font-size: 1.75rem">
        <tbody>
          <tr>
            <td><%= @game.home_team.name %> (<%= @game.is_winner? @game.home_team %>)</td>
            <td id="home-team-runs"><%= @game.home_team_runs %></td>
            <td id="home-team-hits"><%= @game.home_team_hits %></td>
            <td id="home-team-errors"><%= @game.home_team_errors %></td>
          </tr>
          <tr>
            <td><%= @game.away_team.name %> (<%= @game.is_winner? @game.away_team %>)</td>
            <td id="away-team-runs"><%= @game.away_team_runs %></td>
            <td id="away-team-hits"><%= @game.away_team_hits %></td>
            <td id="away-team-errors"><%= @game.away_team_errors %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-sm-8">
      <table class="table table-condensed text-center" style="font-size: 1.3rem;">
        <thead>
          <tr>
            <% @game.innings.each do |inning| %>
              <th style="text-align: center; width: 30px"><%= inning.number %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @game.innings.each do |inning| %>
              <td id="inning-<%= inning.number %>-home"><%= inning.home_team_runs || "-" %></td>
            <% end %>
          </tr>
          <tr>
            <% @game.innings.each do |inning| %>
              <td id="inning-<%= inning.number %>-away"><%= inning.away_team_runs.nil? ? (inning.home_team_runs.nil? ? "-" : "X") : inning.away_team_runs %></td>
            <% end %>
          </tr>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baseball</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>